name: 20
timestamp: 1454143493
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443837785
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  breadcrumb-right: 'Breadcrumb Right'
  home-main: 'Home Main'
  home-sidebar: 'Home Sidebar'
  sidebar-a: 'Sidebar A'
  footer: Footer
