name: 18
timestamp: 1444031743
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443837785
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
