name: 21
timestamp: 1444039565
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443837785
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  home-main: 'Home Main'
  home-sidebar: 'Home Sidebar'
  sidebar-a: 'Sidebar A'
  footer: Footer
